### PR TITLE
Align to cxx version of dragonbox

### LINKED ISSUE #3: to_decimal() panics on some values
## Environment

Last revision on master branch (830d0483bdb048d83b270dd4228e8cf4a31cefbf).

* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-pc-windows-msvc
* **Operating system:** Windows 10 10.0

## Description

The following value triggers an error:

1.0902420340782359E+57

##  How to reproduce

- `cargo test --package dragonbox --test binary64_test test_regression`
=> OK
- add this test to `test_regression()`
```rust
check!(1.0902420340782359E+57);
```
- `cargo test --package dragonbox --test binary64_test test_regression`
=> panic

> assertion failed: (exp as usize) < TABLE_SIZE
> thread 'test_regression' panicked at 'assertion failed: (exp as usize) < TABLE_SIZE', src\div.rs:71:5
> stack backtrace:
>    0: std::panicking::begin_panic_handler
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
>    1: core::panicking::panic_fmt
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
>    2: core::panicking::panic
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:48
>    3: dragonbox::div::divisible_by_power_of_5<24>
>              at .\src\div.rs:71
>    4: dragonbox::is_product_integer_fc
>              at .\src\lib.rs:469
>    5: dragonbox::compute_nearest_normal
>              at .\src\lib.rs:325
>    6: dragonbox::to_decimal
>              at .\src\lib.rs:553
>    7: dragonbox::to_chars::to_chars
>              at .\src\to_chars.rs:38
>    8: dragonbox::buffer::impl$5::write_to_dragonbox_buffer
>              at .\src\buffer.rs:112
>    9: dragonbox::Buffer::format_finite<f64>
>              at .\src\buffer.rs:52
>   10: dragonbox::Buffer::format<f64>
>              at .\src\buffer.rs:30
>   11: binary64_test::to_chars
>              at .\tests\binary64_test.rs:35
>   12: binary64_test::test_regression
>              at .\tests\binary64_test.rs:115
>   13: binary64_test::test_regression::closure$0
>              at .\tests\binary64_test.rs:106
>   14: core::ops::function::FnOnce::call_once<binary64_test::test_regression::closure_env$0,tuple$<> >
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
>   15: core::ops::function::FnOnce::call_once
>              at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\ops\function.rs:248
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

## Misc

I have changed the Cargo.toml to edition 2021 but I don't think this should have any impact.

I noticed that the original C++ source code has received many updates since the port to Rust, but I'm not sure they're relevant to that particular problem. I currently don't have the tools to check this particular value with the original C++ Dragonbox code, unfortunately; I will post an update if I manage to do that test.

### PR DESCRIPTION
**Pull request by magic-akari**
- Closes: #3

### CODE REVIEW

**Comment by magic-akari** [comment]
Hello @dtolnay , I've marked this PR as ready for review. Could you please take a look when convenient? Appreciate your time!

File: src/lib.rs [hunk 1]
```diff
@@ -260,78 +253,66 @@ fn compute_nearest_normal(
...
-            break 'small_divisor_case_label;
-        } else if r < deltai {
+    loop {
+        if r < deltai {
             // Exclude the right endpoint if necessary.
-            if r == 0
-                && !has_even_significand_bits
-                && is_product_integer_fc_pm_half(two_fr, exponent, minus_k)
-            {
+            if r == 0 && !z_result.is_integer && !include_right_endpoint {
```
Comment (leung-ming) [inline src/lib.rs]: Hello,
According to the original code
```c++
                            if ((r | remainder_type_(!z_result.is_integer) |
                                 remainder_type_(interval_type.include_right_endpoint())) == 0) {
```
Should this line to be the following?
```suggestion
            if r == 0 && z_result.is_integer && !include_right_endpoint {
```

Comment (magic-akari) [reply src/lib.rs]: Thank you!

**Review by dtolnay — APPROVED** [review]
Thanks!
